package br.com.mantunes.sped.ui.activity

const val CHAVE_DESTINO : String= "CHAVE_MAIN"
const val CHAVE_ENDERECO : String= "CHAVE_ENDERECO"
const val CHAVE_LOGIN_CLIENTE : String= "CHAVE_LOGIN_CLIENTE"
const val CHAVE_PRODUTO_ARGS : String= "CHAVE_PRODUTO_ARGS"
const val CHAVE_PRODUTO_ID_ARGS : String= "CHAVE_PRODUTO_ID_ARGS"
const val CHAVE_CARRINHO_OPER : String = "CHAVE_CARRINHO_OPER"
const val CHAVE_CARRINHO : String = "CHAVE_CARRINHO"
const val CHAVE_PEDIDO_REGISTRADO_ID_ARGS : String = "CHAVE_PEDIDO_REGISTRADO_ID_ARGS"
const val CHAVE_PEDIDODTO_ARGS : String = "CHAVE_PEDIDODTO_ARGS"
const val CHAVE_CLIENTE_ARGS : String= "CHAVE_CLIENTE_ARGS"
const val CHAVE_CATEGORIA_ID_ARGS : String = "CHAVE_CATEGORIA_ID_ARGS"
const val FILE_PREFERENCE : String= "br.com.alura.aluraesporte.sped"
const val ADICIONA_NO_CARRINHO : String = "Adiciona"
const val DELETE_DO_CARRINHO : String = "Delete"
const val REMOVE_DO_CARRINHO : String = "Remove"