package br.com.mantunes.sped.ui.fragment

const val ID_PRODUTO_INVALIDO = "id do produto inválido"
const val PRODUTO_INVALIDO = "produto inválido"
const val PEDIDO_INVALIDO = "pedido inválido"
const val TOTAL_CARRINHO = "Total:                                         "
const val FALHA_AO_CRIAR_CARRINHO = "Falha ao criar carrinho"
const val FALHA_AO_CRIAR_PEDIDO = "Falha ao criar PEDIDO"
const val FALHA_AO_CRIAR_PAGAMENTO = "Falha ao criar PAGAMENTO"
const val FALHA_AO_CRIAR_ITENS_PEDIDO = "Falha ao criar ITENS DO PEDIDO"
const val FALHA_AO_ATUALIZAR_CARRINHO = "Falha ao atualizar carrinho"
const val CARRINHO_TIPO_OPERACAO_INVALIDA = "Carrinho com tipo de operacao invalido"
const val TITULO_APPBAR_CADASTRO = "Cadastro"
const val TITULO_APPBAR_DADOS_PF = "Dados complementares de pessoa física"
const val INCLUSÃO_ENDERECO = "Inclusão de Endereço"
const val ALTERACAO_ENDERECO = "Alteração de Endereço"
const val CODIGO_CAMERA = 567
const val PROBLEMA_EXTRAIR_CONTEXTO = "Nao inicializou o Context VaiPara"
const val TITULO_APPBAR_ENDERECO_ENTREGA = "Endereço de entrega"
const val TITULO_APPBAR_FORMA_PAGAMENTO = "Forma de pagamento"
const val TITULO_APPBAR_DETALHES_DO_PRODUTO = "Detalhes do Produto"
const val TITULO_APPBAR_PEDIDO_REGISTRADO = "Pedido registrado"
const val TITULO_APPBAR_CARRINHO = "Carrinho"
const val TITULO_APPBAR_CONFIRA_PEDIDO = "Confira seu pedido"
const val TITULO_APPBAR_CATEGORIAS = "Categorias"
const val TITULO_APPBAR_PRODUTOS = "Produtos"

